/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_os_inference */

#ifndef _Included_java_os_inference
#define _Included_java_os_inference
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_os_inference
 * Method:    inference
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 javac java_os_inference.java && java java_os_inference
 */
JNIEXPORT jstring JNICALL Java_java_1os_1inference_inference
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
