/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_onnx_inference */

#ifndef _Included_java_onnx_inference
#define _Included_java_onnx_inference
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_onnx_inference
 * Method:    inference
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_java_1onnx_1inference_inference
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
